- name: Compare host packages with content view
  hosts: "{{ run_host }}"

  tasks:
  - name: Copy python scripts to remote machine
    ansible.builtin.copy:
      src: /runner/project/python_scripts/
      dest: /tmp/python_scripts

  - name: Run Python script
    command: "python3 /tmp/python_scripts/contentview-query-pckg.py {{ satellite_host }} {{ satellite_user }} {{ satellite_pswd }} {{ content_view }} {{ content_view_version }}"
    args:
      chdir: /tmp/python_scripts

  - name: Run Python script
    command: "python3 /tmp/python_scripts/package-repos.py {{ satellite_host }} {{ satellite_user }} {{ satellite_pswd }} {{ content_view }} {{ content_view_version }}"
    args:
      chdir: /tmp/python_scripts