- name: Compare host packages with content view
  hosts: "{{ inventory_host }}"
  vars:
    host_collection: ""
    lifecycle_environment: ""

  tasks:
  - name: Copy python scripts to remote machine
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /tmp/outputs
    with_fileglob: 
      - "{{ playbook_dir }}/files/host*"

  - name: Run host_list_host_collection.py when host_collection_name varaible is length greater than 0.
    ansible.builtin.command: "python3 /tmp/outputs/host_list_host_collection.py  {{ satellite_host }} {{ satellite_user }} {{ satellite_pswd }} {{ host_collection }}" 
    args:
      chdir: /tmp/outputs
    when: host_collection | length > 0

  - name: Run host_list_lifecycle_environment.py when lifecycle_environment_name varaible is length greater than 0.
    ansible.builtin.command: "python3 /tmp/outputs/host_list_lifecycle_environment.py  {{ satellite_host }} {{ satellite_user }} {{ satellite_pswd }} {{ lifecycle_environment }}" 
    args:
      chdir: /tmp/outputs
    when: lifecycle_environment | length > 0

  - name: Run host_applicable_errata.py
    ansible.builtin.command: "python3 /tmp/outputs/host_applicable_errata.py {{ satellite_host }} {{ satellite_user }} {{ satellite_pswd }} host_report_{{ ansible_date_time.iso8601 }}.csv"
    args:
      chdir: /tmp/outputs

  - name: Remove file (delete file)
    ansible.builtin.file:
      src: "{{ item }}"
      state: absent
    with_fileglob: 
      - "/tmp/outputs/*.py