- name: Compare host packages with content view
  hosts: "{{ inventory_host }}"

  tasks:
  - name: Copy python scripts to remote machine
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/"
      dest: /tmp/outputs

  - name: Run Python script
    ansible.builtin.command: "python3 /tmp/outputs/contentview-query-pckg.py {{ satellite_host }} {{ satellite_user }} {{ satellite_pswd }} {{ content_view }} {{ content_view_version }} {{ full_results }}" 
    args:
      chdir: /tmp/outputs

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /tmp/outputs/contentview-query-pckg.py
      state: absent

  - name: Run Python script
    ansible.builtin.command: "python3 /tmp/outputs/package-repos.py {{ satellite_host }} {{ satellite_user }} {{ satellite_pswd }} {{ content_view }} {{ content_view_version }}"
    args:
      chdir: /tmp/outputs

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /tmp/outputs/package-repos.py
      state: absent